name: Update

on:
  watch:
    types: [started]
  schedule:
    - cron: 0,30 * * * *

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"

    - name: Update
      run: |
        curl -L https://raw.githubusercontent.com/pmkol/easymosdns/rules/china_domain_list.txt -o ./etc/mosdns/rules/china_domain_list.txt
        curl -L https://raw.githubusercontent.com/pmkol/easymosdns/rules/gfw_domain_list.txt -o ./etc/mosdns/rules/gfw_domain_list.txt
        curl -L https://raw.githubusercontent.com/pmkol/easymosdns/rules/cdn_domain_list.txt -o ./etc/mosdns/rules/cdn_domain_list.txt
        curl -L https://raw.githubusercontent.com/pmkol/easymosdns/rules/china_ip_list.txt -o ./etc/mosdns/rules/china_ip_list.txt
        curl -L https://raw.githubusercontent.com/pmkol/easymosdns/rules/gfw_ip_list.txt -o ./etc/mosdns/rules/gfw_ip_list.txt
        curl -L https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt -o ./etc/mosdns/rules/ad_domain_list.txt
        curl -L https://www.cloudflare.com/ips-v4 -o ./etc/mosdns/rules/cf_ip_list.txt
        echo '' >> ./etc/mosdns/rules/cf_ip_list.txt
        curl -L https://www.cloudflare.com/ips-v6 -o ./cfipv6.txt
        cat ./cfipv6.txt >> ./etc/mosdns/rules/cf_ip_list.txt
        rm -f ./cfipv6.txt

    - name: Clean
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout --orphan latest_branch
        git add -A
        git commit -am "${{ steps.date.outputs.date }}"
        git branch -D Files
        git branch -m Files

    - name: Push
      run: git push -f origin Files
